### ISSUE TITLE
"Preserve Original 4" option doesn't work

### ISSUE THREAD

**Issue by LouisB3** [KSP-RO/KerbalRenamer#8]
Even if "Preserve Original 4" is checked before game creation, the four orange-suited veterans in the new game will have random genders, stats (Bravery/Stupidity/BadS), and names. Professions are preserved, however.

**Comment by Gordon-Dry** [comment]
Now, on KSP 1.12.3, also "Preserve Original Traits" does not work anymore, all 4 are always pilots.
And I fire them asap as in early career sounding rocket grind is on the schedule.
But the messages that they retired still appears years later.

I'm curious why this old version is still part of the RP-1 install as the devs are usually very strict with compatibilities.

**Comment by Gordon-Dry** [comment]
This seems to be the fix:
https://github.com/KSP-RO/KerbalRenamer/pull/15
